import { NextRequest, NextResponse } from 'next/server'
import { Resend } from 'resend'

const resend = new Resend(process.env.RESEND_API_KEY)

// FIXED EMAIL CONFIGURATION - Always uses working combination
// All emails will be sent from onboarding@resend.dev to kaikang0609@gmail.com
// This ensures emails always work regardless of dynamic parameters
const EMAIL_CONFIG = {
  from: 'Onboarding Assistant <onboarding@resend.dev>',
  to: 'kaikang0609@gmail.com', // All emails go here for testing/demo
}

export async function POST(request: NextRequest) {
  try {
    const body = await request.json()
    const { 
      function_name, 
      parameters,
      employee_name,
      employee_email,
      manager_email 
    } = body

    let subject = ''
    let htmlContent = ''

    // Handle different function calls
    // Note: All emails will be sent to the fixed recipient (kaikang0609@gmail.com)
    switch (function_name) {
      case 'send_email_to_it':
        subject = `[IT SUPPORT] License/Access Request from ${employee_name || parameters.employee_name}`
        htmlContent = `
          <h2>🔧 License/Access Request</h2>
          <p><strong>From:</strong> ${employee_name || parameters.employee_name} (${employee_email})</p>
          <p><strong>Request Type:</strong> ${parameters.request_type || 'General Request'}</p>
          <p><strong>Details:</strong></p>
          <p>${parameters.details || 'No additional details provided.'}</p>
          <hr>
          <p style="color: #666; font-size: 12px;">📧 Intended for: IT Support (it-support@raspberry-coffee.com)</p>
          <p style="color: #666; font-size: 12px;">This email was automatically generated by the onboarding assistant.</p>
        `
        break

      case 'send_email_to_hr':
        subject = `[HR TEAM] Question from ${employee_name || parameters.employee_name}`
        htmlContent = `
          <h2>👥 HR Policy/Benefits Question</h2>
          <p><strong>From:</strong> ${employee_name || parameters.employee_name} (${employee_email})</p>
          <p><strong>Question Type:</strong> ${parameters.question_type || 'General Question'}</p>
          <p><strong>Details:</strong></p>
          <p>${parameters.details || 'No additional details provided.'}</p>
          <hr>
          <p style="color: #666; font-size: 12px;">📧 Intended for: HR Team (hr@raspberry-coffee.com)</p>
          <p style="color: #666; font-size: 12px;">This email was automatically generated by the onboarding assistant.</p>
        `
        break

      case 'send_email_to_manager':
        subject = `[MANAGER] Message from ${employee_name || parameters.employee_name}`
        htmlContent = `
          <h2>💼 Team Member Message</h2>
          <p><strong>From:</strong> ${employee_name || parameters.employee_name} (${employee_email})</p>
          <p><strong>Subject:</strong> ${parameters.subject || 'General Message'}</p>
          <p><strong>Message:</strong></p>
          <p>${parameters.message || parameters.details || 'No message provided.'}</p>
          <hr>
          <p style="color: #666; font-size: 12px;">📧 Intended for: Manager (${manager_email || 'Not specified'})</p>
          <p style="color: #666; font-size: 12px;">This email was automatically generated by the onboarding assistant.</p>
        `
        break

      default:
        return NextResponse.json(
          { error: 'Unknown function name' },
          { status: 400 }
        )
    }

    // Send email using Resend with FIXED configuration
    // Always uses: from onboarding@resend.dev → to kaikang0609@gmail.com
    // This ensures emails always work for demo/testing
    const { data, error } = await resend.emails.send({
      from: EMAIL_CONFIG.from,
      to: EMAIL_CONFIG.to,
      subject: subject,
      html: htmlContent,
    })

    if (error) {
      console.error('Resend error:', error)
      return NextResponse.json(
        { error: 'Failed to send email', details: error },
        { status: 500 }
      )
    }

    return NextResponse.json({
      success: true,
      message: 'Email sent successfully',
      email_id: data?.id,
      recipient: EMAIL_CONFIG.to,
    })

  } catch (error) {
    console.error('Email sending error:', error)
    return NextResponse.json(
      { error: 'Internal server error' },
      { status: 500 }
    )
  }
}

